deploymentMode: SimpleScalable

loki:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  enabled: true
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: https://minio.txuapp.com.
      s3forcepathstyle: true
      insecure: false

  schemaConfig:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  limits_config:
    allow_structured_metadata: false

  extraSecretForConfig:
    name: minio-creds-loki

backend:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  replicas: 1
  affinity: {}
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

write:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  replicas: 1
  affinity: {}
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

read:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  replicas: 1
  affinity: {}
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m


chunksCache:
  enabled: false

serviceMonitor:
  enabled: true
