deploymentMode: SimpleScalable

loki:
  enabled: true
  podDnsConfig:
    options:
      - name: ndots
        value: "1"
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: s3
    s3:
      endpoint: minio.txuapp.com
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      s3forcepathstyle: true
      insecure: false
  schemaConfig:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h
  storage_config:
    boltdb_shipper:
      shared_store: s3
    aws:
      s3: https://minio.txuapp.com/loki-data
      s3forcepathstyle: true
      insecure: false

extraSecretForConfig:
  name: minio-creds-loki

persistence:
  enabled: true
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  size: 5Gi

serviceMonitor:
  enabled: true
