deploymentMode: SimpleScalable

loki:
  auth_enabled: false

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      accessKeyId: JCKNMDS7fLrk8V6ggaKe
      secretAccessKey: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
      s3ForcePathStyle: true
      insecure: true

  commonConfig:
    replication_factor: 1

  compactor:
    working_directory: /var/loki/compactor
    shared_store: s3

# ⚠️ Chỉ dùng các thành phần của SimpleScalable
backend:
  replicas: 1
read:
  replicas: 1
write:
  replicas: 1
gateway:
  replicas: 1
indexGateway:
  replicas: 1

# ⚠️ Đảm bảo KHÔNG cấu hình các component của SingleBinary hoặc Distributed:
singleBinary:
  replicas: 0
distributor:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
compactor:
  replicas: 0
ruler:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# Monitoring
serviceMonitor:
  enabled: true
prometheusRule:
  enabled: false

# Nếu không cần lưu persistent
persistence:
  enabled: false
