# Loki dùng MinIO S3, không tạo PVC
loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      index: loki-index
      ruler: loki-ruler

  storage_config:
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      bucketnames: loki-chunks,loki-index,loki-ruler
      access_key_id: JCKNMDS7fLrk8V6ggaKe
      secret_access_key: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
      s3forcepathstyle: true
      insecure: true

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  compactor:
    shared_store: s3

  # 👉 Tắt tạo PVC hoàn toàn
  persistence:
    enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-http01
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - loki.txuapp.com
  tls:
    - hosts:
        - loki.txuapp.com
      secretName: loki-tls
