deploymentMode: SimpleScalable

loki:
  auth_enabled: false

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/index
      cache_location: /data/loki/index_cache
      shared_store: s3
    aws:
      s3: http://minioadmin:minioadmin@minio.minio.svc.cluster.local.:9000/loki-logs
      s3forcepathstyle: true
      insecure: true

  commonConfig:
    replication_factor: 1

  compactor:
    working_directory: /data/loki/compactor
    shared_store: s3

  ruler:
    storage:
      type: s3
      s3:
        bucketnames: loki-logs
        endpoint: minio.minio.svc.cluster.local.:9000
        access_key_id: JCKNMDS7fLrk8V6ggaKe
        secret_access_key: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
        s3forcepathstyle: true
        insecure: true

  # Bắt buộc với SimpleScalable
  structuredConfig:
    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 1h
      max_chunk_age: 1h
      wal:
        enabled: true
        dir: /var/loki/wal

    memberlist:
      join_members:
        - "loki-memberlist"

  # Thêm để tránh lỗi validation
  limits_config:
    enforce_metric_name: false

persistence:
  enabled: false

read:
  replicas: 1

write:
  replicas: 1

backend:
  replicas: 1

gateway:
  replicas: 1

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: false
