loki:
  config:
    common:
      storage:
        filesystem:
          directory: /var/loki/chunks
    schema_config:
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            period: 24h
            prefix: index_

persistence:
  enabled: true
  size: 10Gi
