# Dùng chế độ mở rộng linh hoạt, không phân tán
deploymentMode: SimpleScalable

# Sử dụng object storage S3 (MinIO)
minio:
  enabled: true

loki:
  auth_enabled: false

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      accessKeyId: JCKNMDS7fLrk8V6ggaKe
      secretAccessKey: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
      s3ForcePathStyle: true
      insecure: true

  commonConfig:
    replication_factor: 1

  compactor:
    working_directory: /var/loki/compactor
    shared_store: s3

# Chỉ bật các service của SimpleScalable
backend:
  replicas: 1
read:
  replicas: 1
write:
  replicas: 1
gateway:
  replicas: 1
indexGateway:
  replicas: 1

# Vô hiệu hóa mọi cấu hình còn lại không cần thiết
singleBinary: null
distributor: null
ingester: null
querier: null
frontend: null
ruler: null
tableManager: null
resultsCache: null
chunksCache: null

# Không bật persistent volume
persistence:
  enabled: false

serviceMonitor:
  enabled: true
prometheusRule:
  enabled: false
