deploymentMode: SimpleScalable

loki:
  enabled: true
  auth_enabled: false

  # Inject biến môi trường từ Secret vào container Loki
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-s3-secret
          key: access_key
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-s3-secret
          key: secret_key

  config:
    common:
      replication_factor: 1

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    memberlist:
      join_members: []  # Vô hiệu hóa cluster join bị lỗi IP 125.x.x.x

    storage_config:
      s3:
        endpoint: https://minio.txuapp.com
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        s3forcepathstyle: true
        insecure: true  # Nếu MinIO không dùng TLS nội bộ, giữ true

    schema_config:
      configs:
        - from: "2022-01-01"
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h

    ruler:
      storage:
        type: s3
        s3:
          bucketnames: loki-ruler
      rule_path: /tmp/loki/rules
      alertmanager_url: http://alertmanager:9093

    limits_config:
      allow_structured_metadata: false

backend:
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

write:
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

read:
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

chunksCache:
  enabled: false

serviceMonitor:
  enabled: true
