deploymentMode: SimpleScalable

loki:
  enabled: true
  auth_enabled: false

  podDnsConfig:
    options:
      - name: ndots
        value: "1"

  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    s3:
      endpoint: minio.txuapp.com
      s3forcepathstyle: true
      insecure: false

  schemaConfig:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

extraSecretForConfig:
  name: minio-creds-loki

serviceMonitor:
  enabled: true

# Disable anti-affinity rules to allow scheduling on any node
affinity: {}

backend:
  affinity: {}
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

write:
  affinity: {}
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

read:
  affinity: {}
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

chunksCache:
  enabled: false  # tránh lỗi thiếu RAM
