deploymentMode: SimpleScalable

loki:
  enabled: true
  auth_enabled: false
  podDnsConfig:
    options:
      - name: ndots
        value: "1"

  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: minio.txuapp.com
      s3forcepathstyle: true
      insecure: false

  schemaConfig:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  limits_config:
    allow_structured_metadata: false

  extraSecretForConfig:
    name: minio-creds-loki

backend:
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  affinity: {}

write:
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  affinity: {}

read:
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  affinity: {}

serviceMonitor:
  enabled: true
