deploymentMode: SingleBinary

singleBinary:
  replicas: 1

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: minio.minio.svc.cluster.local.:9000
      access_key_id: JCKNMDS7fLrk8V6ggaKe
      secret_access_key: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
      s3forcepathstyle: true
      insecure: true

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  compactor:
    working_directory: /data/loki/compactor
    shared_store: s3

  ruler:
    storage:
      type: s3
      s3:
        bucketnames: loki-ruler
        endpoint: minio.minio.svc.cluster.local.:9000
        access_key_id: JCKNMDS7fLrk8V6ggaKe
        secret_access_key: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
        s3forcepathstyle: true
        insecure: true

persistence:
  enabled: false

serviceMonitor:
  enabled: true
