# file: loki-values.yaml

deploymentMode: SimpleScalable
storage:
  type: s3
  s3:
    s3: http://minio.minio.svc.cluster.local:9000
    bucketnames: loki-logs
    region: us-east-1
    secret:
      name: loki-s3-secret
      key: AWS_ACCESS_KEY_ID
      secretKey: AWS_SECRET_ACCESS_KEY

# bật ingress cho API
gateway:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt-http01
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - loki.txuapp.com
    tls:
      - secretName: loki-tls
        hosts:
          - loki.txuapp.com
