deploymentMode: SimpleScalable

loki:
  auth_enabled: false

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: minio.minio.svc.cluster.local.:9000
      accessKeyId: JCKNMDS7fLrk8V6ggaKe
      secretAccessKey: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
      s3ForcePathStyle: true
      insecure: true

  commonConfig:
    replication_factor: 1

  compactor:
    working_directory: /var/loki/compactor
    shared_store: s3

  rulerConfig:
    storage:
      type: s3
      s3:
        bucketnames: loki-ruler
        endpoint: minio.minio.svc.cluster.local.:9000
        access_key_id: JCKNMDS7fLrk8V6ggaKe
        secret_access_key: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
        s3forcepathstyle: true
        insecure: true

singleBinary:
  replicas: 0

backend:
  replicas: 1

read:
  replicas: 1

write:
  replicas: 1

gateway:
  replicas: 1

indexGateway:
  replicas: 1

persistence:
  enabled: false

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: false
