loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: s3
    s3:
      endpoint: http://minio.minio.svc.cluster.local.:9000
      bucketnames: loki-logs
      access_key_id: JCKNMDS7fLrk8V6ggaKe
      secret_access_key: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
      s3forcepathstyle: true

backend:
  persistence:
    enabled: false
write:
  persistence:
    enabled: false
chunksCache:
  persistence:
    enabled: false

