loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    memberlist:
      join_members:
        - loki-memberlist

    common:
      storage:
        filesystem:
          directory: /var/loki/chunks

    schema_config:
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m

persistence:
  enabled: true
  size: 10Gi
