deploymentMode: SimpleScalable

loki:
  enabled: true
  auth_enabled: false
  commonConfig:
    replication_factor: 1

  storage_config:
    aws:
      s3: https://minio.txuapp.com/loki-data
      s3forcepathstyle: true
      insecure: false

  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin

  # storage:
  #   type: s3
  #   s3:
  #     endpoint: minio.txuapp.com
  #     bucketnames: loki-data
  #     s3forcepathstyle: true
  #     insecure: true

  schemaConfig:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  limits_config:
    allow_structured_metadata: false

backend:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

write:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

read:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

chunksCache:
  enabled: false

serviceMonitor:
  enabled: true
