loki:
  auth_enabled: false

  storage:
    type: filesystem

  persistence:
    enabled: true
    storageClassName: local-path
    size: 10Gi

  schemaConfig:
    configs:
      - from: "2022-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v12
        index:
          prefix: loki_index_
          period: 24h

gateway:
  enabled: true
