deploymentMode: SimpleScalable

loki:
  enabled: true

  podDnsConfig:
    options:
      - name: ndots
        value: "1"

  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    s3:
      endpoint: minio.txuapp.com
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      s3forcepathstyle: true
      insecure: false

  schemaConfig:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  #  KHÔNG dùng phần này ở schemaConfig nếu đã có `storage.s3` đúng phía trên
  # aws:
  #   s3: https://minio.txuapp.com/loki-chunks
  #   s3forcepathstyle: true
  #   insecure: false

extraSecretForConfig:
  name: minio-creds-loki

backend:
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi

write:
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi

read:
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi

serviceMonitor:
  enabled: true
