loki:
  auth_enabled: false

  storage:
    type: s3

  config:
    common:
      storage:
        s3:
          endpoint: minio.minio.svc.cluster.local.:9000
          bucketnames: loki-data
          access_key_id: loki
          secret_access_key: supersecret
          insecure: true
          s3forcepathstyle: true
    schema_config:
      configs:
        - from: "2024-06-01"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
