deploymentMode: SimpleScalable

loki:
  enabled: true
  auth_enabled: false
  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    bucketNames: loki-data    #  Dùng 1 bucket duy nhất
    s3:
      endpoint: http://minio.txuapp.com  #  Dùng http nếu bạn đang truy cập nội bộ (không có TLS)
      bucketnames: loki-data             #  Dùng chung 1 bucket cho tất cả
      s3forcepathstyle: true             #  Bắt buộc để không chia domain phụ
      insecure: true                     #  Cho phép HTTP nếu MinIO không dùng TLS

  schemaConfig:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  limits_config:
    allow_structured_metadata: false

backend:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

write:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

read:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

chunksCache:
  enabled: false

serviceMonitor:
  enabled: true
