deploymentMode: SimpleScalable

loki:
  enabled: true
  auth_enabled: false
  # Inject biến môi trường từ Secret vào container Loki
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-s3-secret
          key: access_key
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-s3-secret
          key: secret_key

  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: https://minio.txuapp.com
      access_key_id: 1WgQOTobDw5N1SH6nCDt
      secret_access_key: 077An00VanXOmHe1UsQvcdGSGK1WYLW8ad9FSfyN
      s3forcepathstyle: true
      insecure: true

  schemaConfig:
    configs:
      - from: 2022-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  limits_config:
    allow_structured_metadata: false

backend:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

write:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

read:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-secret
  replicas: 2
  persistence:
    enabled: true
    storageClass: nfs-client
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

chunksCache:
  enabled: false

serviceMonitor:
  enabled: true
