loki:
  auth_enabled: false

  storage:
    bucketNames:
      chunks: loki-logs
      ruler: loki-logs
      admin: loki-logs
    type: s3

  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/index
      cache_location: /data/loki/index_cache
      shared_store: s3
    aws:
      s3: http://minioadmin:minioadmin@minio.minio.svc.cluster.local.:9000/loki-logs
      s3forcepathstyle: true
    index_gateway:
      mode: "ring"

  schema_config:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  persistence:
    enabled: false

  commonConfig:
    replication_factor: 1
