deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-logs
    s3:
      endpoint: minio.minio.svc.cluster.local.:9000
      accessKeyId: JCKNMDS7fLrk8V6ggaKe
      secretAccessKey: dvhxhf8ogYpJGQq8s3L5VzeN1h3qvJUs1WjUrcy2
      s3ForcePathStyle: true
      insecure: true

  compactor:
    working_directory: /var/loki/compactor
    shared_store: s3

singleBinary:
  replicas: 1
  persistence:
    enabled: false

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: false
