loki:
  auth_enabled: false

  persistence:
    enabled: false

  storage:
    type: filesystem

schemaConfig:
  configs:
    - from: "2022-01-01"
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: loki_index_
        period: 24h

gateway:
  enabled: true
