# loki-values.yaml
loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory

  storage_config:
    filesystem:
      directory: /var/loki

  schema_config:
    configs:
      - from: 2024-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v12
        index:
          prefix: index_
          period: 24h

  limits_config:
    retention_period: 168h  # 7 ngày
