mode: standalone

replicas: 1

resources:
  requests:
    memory: 512Mi
    cpu: 500m

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path

rootUser: loki
rootPassword: supersecret

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-http01
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - hosts:
        - minio.txuapp.com
      secretName: minio-tls
  hosts:
    - minio.txuapp.com
