config:
  clients:
    - url: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml

  snippets:
    extraScrapeConfigs: |
      - job_name: backend-job-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: backend-job
              __path__: /mnt/backend_logs/*/*/*.log
        pipeline_stages:
          - regex:
              expression: "/mnt/hrm-logs/(?P<namespace>[^/]+)/(?P<app>[^/]+)/(?P<pod>[^/]+)_(?P<stream>[^.]+)\\.log"
              source: filename
          - labels:
              namespace:
              app:
              pod:
              stream:
          - replace:
              expression: ".*"
              replace: "${namespace}/${app}"
              source: namespace
          - labels:
              job:
          - hostname:
              source: fqdn
              label: node_name
  
extraVolumes:
  - name: backend-logs-mount
    persistentVolumeClaim:
      claimName: promtail-logs-pvc

extraVolumeMounts:
  - name: backend-logs-mount
    mountPath: /mnt/backend_logs

rbac:
  create: true

serviceAccount:
  create: true

# podDnsConfig:
#   options:
#     - name: ndots
#       value: "1"

daemonset:
  enabled: true

deployment:
  enabled: true
  replicas: 1
