config:
  clients:
    - url: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml

extraScrapeConfigs:
  - job_name: backend-hrm
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend-hrm
          app: hrm
          namespace: backend
          __path__: /mnt/backend-logs/*.log

extraVolumes:
  - name: backend-logs
    persistentVolumeClaim:
      claimName: promtail-logs-pvc

extraVolumeMounts:
  - name: backend-logs
    mountPath: /mnt/backend-logs
    readOnly: true

rbac:
  create: true

serviceAccount:
  create: true

podDnsConfig:
  options:
    - name: ndots
      value: "1"

daemonset:
  enabled: true


deployment:
  enabled: true
  replicas: 1
