config:
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml

  scrape_configs:
    - job_name: backend-logs
      static_configs:
        - targets:
            - localhost
          labels:
            job: backend
            host: backend-host
            __path__: /mnt/backend-logs/*.log

extraVolumes:
  - name: backend-logs
    persistentVolumeClaim:
      claimName: promtail-backend-logs-pvc
  - name: positions
    persistentVolumeClaim:
      claimName: promtail-positions-pvc

extraVolumeMounts:
  - name: backend-logs
    mountPath: /mnt/backend-logs
    readOnly: true
  - name: positions
    mountPath: /run/promtail

rbac:
  create: true

serviceAccount:
  create: true

# Thêm cấu hình ndots:1
podDnsConfig:
  options:
    - name: ndots
      value: "1"
