apiVersion: v1
kind: PersistentVolume
metadata:
  name: promtail-backend-logs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.98.150
    path: /mnt/data/nfs/backend/hrm/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promtail-backend-logs-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  volumeName: promtail-backend-logs-pv
