apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promtail-positions-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
