config:
  clients:
    - url: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml

extraScrapeConfigs:
  - job_name: backend-hrm
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend-hrm
          app: hrm
          namespace: backend
          __path__: /mnt/hrm-logs/*.log

extraVolumes:
  - name: hrm-logs
    persistentVolumeClaim:
      claimName: promtail-logs-pvc

extraVolumeMounts:
  - name: hrm-logs
    mountPath: /mnt/hrm-logs

rbac:
  create: true

serviceAccount:
  create: true

# podDnsConfig:
#   options:
#     - name: ndots
#       value: "1"

daemonset:
  enabled: false


deployment:
  enabled: true
  replicas: 1
