promtail:
  config:
    clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml
    scrape_configs:
    - job_name: hrm-backend-logs
      static_configs:
      - labels:
          __path__: /mnt/data/backend/*.log
          app: hrm
          job: hrm-backend
          namespace: backend
        targets:
        - localhost
  enabled: true
  extraVolumeMounts:
  - mountPath: /mnt/data/backend
    name: backend-logs
    readOnly: true
  - mountPath: /run/promtail
    name: positions
    readOnly: false
  extraVolumes:
  - hostPath:
      path: /mnt/data/backend
      type: DirectoryOrCreate
    name: backend-logs
  - name: positions
    emptyDir: {}
