config:
  clients:
    - url: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml

# extraScrapeConfigs: |
#   - job_name: hrm-nfs-logs
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: hrm-nfs
#           __path__: /mnt/hrm-logs/**/*.log
#     pipeline_stages:
#       - regex:
#           expression: '(?P<namespace>[^/]+)/(?P<app>[^/]+)/.*\.log'
#       - labels:
#           namespace:
#           app
  snippets:
    extraScrapeConfigs: |
      - job_name: hrm-nfs
        static_configs:
          - targets:
              - localhost
            labels:
              job: hrm-nfs
              app: hrm
              namespace: backend
              __path__: /mnt/hrm-logs/**/*.log
        relabel_configs:
          - source_labels: ['__path__']
            target_label: filename
          - source_labels: ['__path__']
            regex: '.*/(?P<namespace>[^/]+)/(?P<app>[^/]+)/.*\.log'
            replacement: '$1'
            target_label: 'namespace'
          - source_labels: ['__path__']
            regex: '.*/(?P<namespace>[^/]+)/(?P<app>[^/]+)/.*\.log'
            replacement: '$2'
            target_label: 'app'

extraVolumes:
  - name: hrm-logs
    persistentVolumeClaim:
      claimName: promtail-logs-pvc

extraVolumeMounts:
  - name: hrm-logs
    mountPath: /mnt/hrm-logs

rbac:
  create: true

serviceAccount:
  create: true

# podDnsConfig:
#   options:
#     - name: ndots
#       value: "1"

daemonset:
  enabled: false


deployment:
  enabled: true
  replicas: 1
