config:
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml

  # ⚠️ Quan trọng: Bạn đang dùng deployment, cần khai báo trong extraScrapeConfigs
  # chứ không phải scrape_configs ở đây
  # → Phần scrape_configs cũ đã được xoá khỏi đây

extraScrapeConfigs:
  - job_name: backend-hrm
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend-hrm
          app: hrm
          namespace: backend
          __path__: /mnt/backend-logs/*.log

extraVolumes:
  - name: backend-logs
    persistentVolumeClaim:
      claimName: promtail-backend-logs-pvc
  - name: positions
    persistentVolumeClaim:
      claimName: promtail-positions-pvc

extraVolumeMounts:
  - name: backend-logs
    mountPath: /mnt/backend-logs
    readOnly: true
  - name: positions
    mountPath: /run/promtail

rbac:
  create: true

serviceAccount:
  create: true

podDnsConfig:
  options:
    - name: ndots
      value: "1"

daemonset:
  enabled: false


deployment:
  enabled: true
  replicas: 1
