scrape_configs:
  - job_name: hrm-backend-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: hrm-backend
          namespace: backend
          app: hrm
          __path__: /mnt/data/backend/*.log
