promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: hrm-backend-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: hrm-backend
              namespace: backend
              app: hrm
              filename: "backend.log"  # <-- label tĩnh (nếu ko muốn tĩnh thì dùng relabel)
              __path__: /mnt/data/backend/*.log
        pipeline_stages:
          - match:
              selector: '{job="hrm-backend"}'
              stages:
                - regex:
                    expression: '/mnt/data/backend/(?P<filename>.+)\.log'
                - labels:
                    filename: filename
