apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: refresh-ecr-binding
  namespace: backend
subjects:
  - kind: ServiceAccount
    name: refresh-ecr-sa
    namespace: backend
roleRef:
  kind: Role
  name: refresh-ecr-role
  apiGroup: rbac.authorization.k8s.io
