apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-nfs-pvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
      
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nexus-pvc
#   namespace: nexus
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: manual
#   resources:
#     requests:
#       storage: 10Gi



