apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      dnsPolicy: ClusterFirst
      serviceAccountName: jenkins-sa  
      # initContainers:
      #   - name: fix-permissions
      #     image: busybox
      #     command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
      #     volumeMounts:
      #       - name: jenkins-home
      #         mountPath: /var/jenkins_home
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: agent  
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-nfs-pvc
        # - name: jenkins-home
        #   hostPath:
        #     path: /mnt/data/jenkins
        #     type: DirectoryOrCreate 
