apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ if .Values.persistence.storageClassName }}{{ .Values.persistence.storageClassName }}{{ else }}manual{{ end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

