global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'vothinhuydt@gmail.com'
  smtp_auth_username: 'vothinhuydt@gmail.com'
  smtp_auth_password: 'grjlsgcaybtvzapr'
  smtp_require_tls: true

route:
  receiver: 'gmail-notify'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 1h

receivers:
  - name: 'gmail-notify'
    email_configs:
      - to: 'vothinhuydt@gmail.com'
        send_resolved: true
