
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hrm-replica-alert
  namespace: monitoring
  labels:
    role: hrm-rules
    release: prometheus-stack  # phải khớp với tên release helm
spec:
  groups:
    - name: hrm.rules
      rules:
        - alert: HrmHighReplicaCount
          expr: |
            kube_deployment_status_replicas{deployment="hrm", namespace="backend"} > 2
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "HRM deployment has scaled up (> 2 replicas)"
            description: "The HRM deployment in namespace 'backend' has more than 2 replicas."