
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hrm-replica-alert
  namespace: backend
  labels:
    role: hrm-rules             # Sử dụng role này để map với cấu hình trong prometheus
    release: prometheus-stack  # Phải khớp với release helm
spec:
  groups:
    - name: hrm.rules
      rules:
        - alert: HrmHighReplicaCount
          expr: |
            kube_deployment_status_replicas{deployment="hrm", namespace="backend"} >= 4
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "HRM deployment has scaled up (>= 04 replicas)"
            description: "Triển khai HRM trong không gian 'backend' đã vượt hơn 03 bản sao"