apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hrm-alert-rules
  namespace: monitoring   # Namespace của Prometheus
spec:
  groups:
    - name: hrm.rules
      rules:
        # - alert: HRMHighCPU
        #   expr: |
        #     avg by(pod) (
        #       rate(container_cpu_usage_seconds_total{namespace="backend", pod=~"hrm.*"}[2m])
        #       /
        #       on(pod) kube_pod_container_resource_requests_cpu_cores{namespace="backend", pod=~"hrm.*"}
        #     ) * 100 > 90
        #   for: 1m
        #   labels:
        #     severity: warning
        #   annotations:
        #     summary: "HRM Pod CPU usage > 90%"
        #     description: "Pod {{ $labels.pod }} is using more than 90% CPU request"
        - alert: HRMReplicaNearMax
          expr: |
            kube_horizontalpodautoscaler_status_current_replicas{namespace="backend", name="hrm"} >= 4
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "HRM app has scaled to 4 or more replicas"
            description: "HRM HPA has scaled up to {{ $value }} pods (max is 5)"

