apiVersion: batch/v1
kind: CronJob
metadata:
  name: jenkins-backup
  namespace: jenkins
spec:
  suspend: true                       # khong chay theo lich
  schedule: "0 * * * *"               # chay moi gio
  successfulJobsHistoryLimit: 1       # chi giu mot jo hoan thanh gan nhat
  failedJobsHistoryLimit: 1           # giu lai mot job that bai gan nhat
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60    # tu dong xoa pod sau 60 giay
      template:
        spec:
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          dnsPolicy: ClusterFirst
          containers:
            - name: backup-to-minio
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              image: vothinhuydt/cronjob:txu
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: minio-creds
                      key: MINIO_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-creds
                      key: MINIO_SECRET_ACCESS_KEY
                - name: MC_CONFIG_DIR #MC_CONFIG_DIR được cấu hình trong env:, để cả trong quá trình chạy mc lẫn khi bạn kubectl exec vào container, thì lệnh mc đều biết đọc đúng config.
                  value: /mc-config
              volumeMounts:
                - name: jenkins-home
                  mountPath: /var/jenkins_home
                - name: mc-config
                  mountPath: /mc-config        
              command:
              - sh
              - -c
              - |
                export MC_CONFIG_DIR=/mc-config
                mc alias set minio https://minio.txuapp.com $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
                echo "[Backup] Archiving Jenkins data..."
                tar czf /tmp/jenkins-backup.tar.gz -C /var/jenkins_home . --ignore-failed-read
                echo "[Backup] Uploading to MinIO..."
                mc cp /tmp/jenkins-backup.tar.gz minio/jenkins-data/jenkins-$(date +%Y%m%d%H%M%S).tar.gz
                echo "Done"
          restartPolicy: OnFailure
          volumes:
            - name: jenkins-home
              nfs:
                server: 192.168.98.150
                path: /mnt/data/nfs/jenkins
            - name: mc-config
              emptyDir: {}
