apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-ecr-secret
  namespace: backend
spec:
  suspend: true                       # khong chay theo lich
  schedule: "0 */6 * * *"             # Chay moi 6 gio
  successfulJobsHistoryLimit: 1       # chi giu mot jo hoan thanh gan nhat
  failedJobsHistoryLimit: 1           # giu lai mot job that bai gan nhat
  jobTemplate:
    spec:
      template:
        spec:
          ttlSecondsAfterFinished: 60    # tu dong xoa pod sau 1 phut
          serviceAccountName: refresh-ecr-sa
          containers:
            - name: refresh-ecr
              image: amazonlinux:2
              command: ["/bin/sh", "-c"]
              args:
                - |
                  yum install -y -q awscli curl tar gzip > /dev/null
                  curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                  install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
                  export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                  export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                  export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
                  kubectl create secret docker-registry ecr-secret --docker-server=211125364313.dkr.ecr.ap-southeast-1.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password --region ap-southeast-1) --docker-email=vovantungdt123@gmail.com -n backend
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-creds-backend
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-creds-backend
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      name: aws-creds-backend
                      key: AWS_REGION
          restartPolicy: OnFailure
