apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-nfs-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.98.150
    path: /mnt/data/nfs/jenkins
  persistentVolumeReclaimPolicy: Retain

