apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: agent   
  selector:
    app: jenkins
