apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-ingress-controller
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-kong
  template:
    metadata:
      labels:
        app: ingress-kong
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: ingress-controller
          image: kong/kubernetes-ingress-controller:3.5
          env:
            - name: KONG_ADMIN_URL
              value: "http://kong-admin.kong.svc.cluster.local:8001"
            - name: KONG_DATABASE
              value: "postgres"
            - name: CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY
              value: "true"
            - name: CONTROLLER_INGRESS_CLASS
              value: "kong"
            - name: CONTROLLER_PUBLISH_SERVICE
              value: "kong/kong-proxy"
            # Đảm bảo không giới hạn namespace nào
            # Không khai báo KONG_WATCH_NAMESPACE tức là watch toàn cluster
          ports:
            - name: metrics
              containerPort: 10255
---
apiVersion: v1
kind: Service
metadata:
  name: kong-ingress-metrics
  namespace: kong
spec:
  ports:
    - name: metrics
      port: 10255
      targetPort: metrics
  selector:
    app: ingress-kong
