apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: hrm-client-jwt
  namespace: backend
consumerRef: hrm-client
type: jwt
config:
  key: hrm-client        # 👈 Trùng với "iss" trong token
  secret: tungxuyenuyen        # 👈 Trùng với secret dùng để ký
  algorithm: HS256
