apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
  namespace: kong
plugin: jwt
config:
  uri_param_names:
    - jwt
  claims_to_verify:
    - exp
  key_claim_name: kid
  secret_is_base64: false
