apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-ingress-controller
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-kong
  template:
    metadata:
      labels:
        app: ingress-kong
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: ingress-controller
          image: kong/kubernetes-ingress-controller:3.5
          env:
            - name: CONTROLLER_LOG_LEVEL
              value: debug
            - name: KONG_ADMIN_URL
              value: "http://kong-kong-admin.kong.svc.cluster.local:8001"
            - name: KONG_DATABASE
              value: "postgres"
