replicaCount: 1

ingressClass: kong

env:
  CONTROLLER_KONG_ADMIN_URL: "http://kong-kong-admin.kong.svc.cluster.local:8001"
  CONTROLLER_KONG_ADMIN_TLS_VERIFY: "false"
  CONTROLLER_DATABASE: "postgres"
  CONTROLLER_PUBLISH_SERVICE: "kong/kong-kong-proxy"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

image:
  repository: kong/kubernetes-ingress-controller
  tag: "3.5"
  pullPolicy: IfNotPresent

rbac:
  create: true

serviceAccount:
  create: true

logLevel: info

# Optional: Tùy chọn nếu bạn cần chỉ định namespace cụ thể để theo dõi
watchNamespace: ""

# Không cài lại CRDs nếu bạn đã cài từ chart `kong/kong` hoặc thủ công
ingressController:
  installCRDs: false
