apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-ingress-controller
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-kong
  template:
    metadata:
      labels:
        app: ingress-kong
    spec:
      containers:
        - name: ingress-controller
          image: kong/kubernetes-ingress-controller:3.5
          args:
            - /kong-ingress-controller
            - --kong-admin-url=http://kong-kong-admin.kong.svc.cluster.local:8001
            - --ingress-class-name=kong
          env:
            - name: CONTROLLER_LOG_LEVEL
              value: debug
            - name: KONG_DATABASE
              value: "postgres"
