# kong-access-backend.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-ingress-role
  namespace: backend
rules:
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongconsumers", "kongplugins", "kongcredentials"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-ingress-bind
  namespace: backend
subjects:
  - kind: ServiceAccount
    name: kong-ingress-controller
    namespace: kong
roleRef:
  kind: Role
  name: kong-ingress-role
  apiGroup: rbac.authorization.k8s.io
