apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
  namespace: backend # thêm dòng này
config:
  uri_param_names:
  - jwt
  claims_to_verify:
  - exp
  key_claim_name: iss
plugin: jwt
