grafana:
  adminUser: admin
  adminPassword: Phan@123
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.txuapp.com
    paths:
      - /
    pathType: ImplementationSpecific

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - prometheus.txuapp.com
    paths:
      - /
    pathType: ImplementationSpecific
  

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - alertmanager.txuapp.com
    paths:
      - /
    pathType: ImplementationSpecific

